### ISSUE TITLE
NullReferenceException crash when attempting to launch craft #2. Also missile mishaps.

### ISSUE THREAD

**Issue by JovietUnion** [BrettRyland/BDArmory#506]
**Describe the bug**
Launching a craft for the first time is fine, but you can't drop any BDA bombs or missiles. BDAE stuff works though, albeit with the cluster missile having a premature detonation after the 2nd missile launch, with the rest of the missiles not even detonating.
But after launching another craft, the game CTDs with the following error on the log:
NullReferenceException: Object reference not set to an instance of an object

**To Reproduce**
Please provide the steps to reproduce the behaviour:
launch a craft from VAB or SPH with this mod and the prerequisites installed.
Then revert and launch a second craft. The game should CTD

**Expected behaviour**
I was expecting to be able to launch as many craft as I needed and drop all bombs and missiles.

**Logs**
Please attach your `<KSP Directory>/KSP.log` file.
[KSP.log](https://github.com/BrettRyland/BDArmory/files/11304658/KSP.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/62820134/233860592-f9dd9100-efa5-4f07-846b-71eb1fb4a6be.png)

**Additional context**

**Comment by BrettRyland** [comment]
v1.6.0.1 of BDArmory had an issue with firing missiles that was fixed in v1.6.0.2, which should fix the issue you're having with being able to fire bombs and missiles and may also help with the cluster missile.

However, the CTD looks to be occuring due to an exception in KSP's PQS (Procedural Quadtree Sphere, the planet terrain generation algorithm) system. I'm not sure what would cause that, but verifying your KSP install in Steam (which I see you're using) would probably be a good start.

**Comment by JovietUnion** [comment]
hmm. I upgraded to 1.6.0.2, and the missiles now work. What I noticed now was that the cluster missiles still won't work, and now this terrain glitch appears, which causes my craft to crash, and the game shortly after follows suit.

![image](https://user-images.githubusercontent.com/62820134/233874324-4d878c89-c97c-4799-8196-146b2919980b.png)

log
[KSP.log](https://github.com/BrettRyland/BDArmory/files/11305329/KSP.log)

**Comment by JovietUnion** [comment]
Yeah, the cluster missiles, which I modded in the cfgs to be GPS guided, don't drop the submunitions. I checked the configs as well, shouldn't there be a deploy height or something?

**Comment by parizhh** [comment]
I also had trouble firing missiles. I got the last BD armory version and missiles not work, theyre not firing, planes are just flying one behind the other. And ammo got "vanished" just left .50 cal.

**Comment by BrettRyland** [comment]
> hmm. I upgraded to 1.6.0.2, and the missiles now work. What I noticed now was that the cluster missiles still won't work, and now, when I revert to launch, this terrain glitch appears, which causes my craft to crash, and the game shortly after follows suit.

I'm unable to reproduce this, but it looks like it's an issue with KSP's PQS system. Your log shows the exception
```
[EXC 20:07:28.399] NullReferenceException: Object reference not set to an instance of an object
  PQS.Mod_OnVertexBuild (PQS+VertexBuildData data) (at <4b449f2841f84227adfaad3149c8fdba>:0)
  PQS.BuildQuad (PQ quad) (at <4b449f2841f84227adfaad3149c8fdba>:0)
  PQ.Build () (at <4b449f2841f84227adfaad3149c8fdba>:0)
  PQ.SetVisible () (at <4b449f2841f84227adfaad3149c8fdba>:0)
  PQ.UpdateVisibility () (at <4b449f2841f84227adfaad3149c8fdba>:0)
  PQ.UpdateSubdivision () (at <4b449f2841f84227adfaad3149c8fdba>:0)
  PQ.UpdateSubdivision () (at <4b449f2841f84227adfaad3149c8fdba>:0)
  PQ.UpdateSubdivision () (at <4b449f2841f84227adfaad3149c8fdba>:0)
  PQ.UpdateSubdivision () (at <4b449f2841f84227adfaad3149c8fdba>:0)
  PQ.UpdateSubdivision () (at <4b449f2841f84227adfaad3149c8fdba>:0)
  PQS.UpdateQuadsInit () (at <4b449f2841f84227adfaad3149c8fdba>:0)
  PQS.StartSphere (System.Boolean force) (at <4b449f2841f84227adfaad3149c8fdba>:0)
  PQS.StartUpSphere () (at <4b449f2841f84227adfaad3149c8fdba>:0)
  PhysicsRangeExtender.TerrainExtender.UpdateSphere () (at <8d8b045516a343de9b8cff73538406ea>:0)
  PhysicsRangeExtender.PhysicsRangeExtender.Start () (at <8d8b045516a343de9b8cff73538406ea>:0)
  UnityEngine.DebugLogHandler:LogException(Exception, Object)
  ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
  UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[ERR 20:07:29.606] PQS Kerbin: Restarted
```
when it should be showing
```
[LOG 14:12:05.150] [PhysicsRangeExtender]:  Updating ranges
```
which is likely the reason why your game is crashing.
If you haven't already, verify the integrity of your KSP install with steam (right click KSP in steam -> properties -> Local Files -> Verify integrity of game files...) and also remove and reinstall PRE.


> Yeah, the cluster missiles, which I modded in the cfgs to be GPS guided, don't drop the submunitions. I checked the configs as well, shouldn't there be a deploy height or something?

You should ask about these in the [BDA-E issues](https://github.com/BrettRyland/BDArmory-Extended/issues) (it's maintained by some devs from BDA other than me). I'm not sure how experimental they are.

**Comment by JovietUnion** [comment]
Nevermind. It turns out my hardware was the root cause of the issue.

Sorry for the inconvienience. Have a good evening.
